spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simplepays
    
  jpa:
    hibernate:
      ddl-auto: update
#  servlet:
#    multipart:
#      max-file-size: 128KB
#      max-request-size: 128KB
        
        
    
server:
  port: 8083



#  mail:
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
#    host: smtp.gmail.com
#    port: 587
#    username: aroratheaksh@gmail.com
#    password: gopb gjcx vigy pllz

        